ARG ELK_VERSION
# https://www.docker.elastic.co/
FROM docker.elastic.co/kibana/kibana:7.13.0-arm64
# FROM docker.elastic.co/kibana/kibana:8.4.2
# Add your kibana plugins setup here
# Example: RUN kibana-plugin install <name|url>
