ARG ELK_VERSION


# MAC
FROM docker.elastic.co/logstash/logstash:7.11.0-arm64
# Linux
# FROM docker.elastic.co/logstash/logstash:${ELK_VERSION}-linux/amd64

# Add your logstash plugins setup here
# Example: RUN logstash-plugin install logstash-filter-json
